"""Resumate agent-core: a public-API-only foundation for external agents.

The package is the client-side half of the frozen Agent operation API contract
(docs/agent/agent-operation-api.md). It talks to the public REST API only and
never touches the business database (contract C-09).
"""

from .checkpoint import CheckpointStore, build_run_state, messages_from_run_state
from .compaction import CompactionPolicy, estimate_context_tokens, should_compact
from .client import ResumateClient
from .config import AgentCoreSettings
from .errors import ApiClientError, ErrorCode, MalformedResponseError, TransportError
from .openai_provider import OpenAICompatibleError, OpenAICompatibleProvider
from .models import (
    AgentMessage,
    AgentSession,
    CapabilityResponse,
    DiffItem,
    PatchApplyRequest,
    PatchApplyResponse,
    PatchPreviewResponse,
    PatchRequest,
    PatchValidationError,
    PatchValidationResponse,
    PendingAction,
    PendingActionResponse,
    ResumeBasics,
    ResumeDocument,
    ResumeEntry,
    ResumeSection,
    TurnResult,
    TurnState,
    UserTurn,
    UserTurnResponse,
    WorkingDocument,
    WorkingDocumentResponse,
)
from .patches import (
    PatchBuilder,
    build_apply_request,
    build_patch,
    remove_entry,
    remove_section,
    set_basics,
    upsert_entry,
    upsert_section,
)
from .runtime import (
    AgentRuntime,
    BudgetExceeded,
    CancellationToken,
    CompactionEvent,
    ErrorEvent,
    FinalizeEvent,
    Message,
    MessageEvent,
    ModelProvider,
    ModelResponse,
    PendingActionEvent,
    RunBudget,
    RunEvent,
    ToolCall,
    ToolProgressEvent,
)
from .session import SessionJournal
from .skills import Skill, SkillLoader, SkillNotFoundError, parse_frontmatter
from .tools import (
    TOOLS,
    Tool,
    ToolArgumentError,
    UnknownToolError,
    call_tool,
    get_tool,
    list_tools,
    openai_tool_specs,
    tool_specs,
)
from .turn import TurnSession, make_idempotency_key

__all__ = [
    "AgentCoreSettings",
    "AgentMessage",
    "AgentRuntime",
    "AgentSession",
    "ApiClientError",
    "BudgetExceeded",
    "CancellationToken",
    "CapabilityResponse",
    "CheckpointStore",
    "CompactionEvent",
    "CompactionPolicy",
    "DiffItem",
    "ErrorCode",
    "ErrorEvent",
    "FinalizeEvent",
    "MalformedResponseError",
    "Message",
    "MessageEvent",
    "ModelProvider",
    "ModelResponse",
    "OpenAICompatibleError",
    "OpenAICompatibleProvider",
    "PatchApplyRequest",
    "PatchApplyResponse",
    "PatchBuilder",
    "PatchPreviewResponse",
    "PatchRequest",
    "PatchValidationError",
    "PatchValidationResponse",
    "PendingAction",
    "PendingActionEvent",
    "PendingActionResponse",
    "ResumeBasics",
    "ResumeDocument",
    "ResumeEntry",
    "ResumeSection",
    "ResumateClient",
    "RunBudget",
    "RunEvent",
    "SessionJournal",
    "TurnState",
    "Skill",
    "SkillLoader",
    "SkillNotFoundError",
    "TOOLS",
    "Tool",
    "ToolArgumentError",
    "ToolCall",
    "ToolProgressEvent",
    "TransportError",
    "TurnResult",
    "TurnSession",
    "UnknownToolError",
    "UserTurn",
    "UserTurnResponse",
    "WorkingDocument",
    "WorkingDocumentResponse",
    "build_apply_request",
    "build_patch",
    "build_run_state",
    "call_tool",
    "estimate_context_tokens",
    "get_tool",
    "list_tools",
    "make_idempotency_key",
    "messages_from_run_state",
    "openai_tool_specs",
    "parse_frontmatter",
    "remove_entry",
    "remove_section",
    "set_basics",
    "should_compact",
    "tool_specs",
    "upsert_entry",
    "upsert_section",
]

__version__ = "0.1.0"
