"""create resume tables"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '465b7e6f13db'
down_revision: Union[str, Sequence[str], None] = 'ccb808fe65a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.Column('affected_sections', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('parent_version_id', sa.String(length=36), nullable=True),
    sa.Column('base_version_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('profile_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('current_version_id', sa.String(length=36), nullable=True),
    sa.Column('lifecycle', sa.String(length=32), nullable=False),
    sa.Column('save_state', sa.String(length=32), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('restore_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_owner_id'), 'resumes', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_owner_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_table('resume_versions')
    # ### end Alembic commands ###
