"""create job_description table"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ab5564e4c8af'
down_revision: Union[str, Sequence[str], None] = '465b7e6f13db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('bound_resume_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_bound_resume_id'), 'job_descriptions', ['bound_resume_id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_owner_id'), 'job_descriptions', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_descriptions_owner_id'), table_name='job_descriptions')
    op.drop_index(op.f('ix_job_descriptions_bound_resume_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
