"""create user settings table"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b7f4a2c9d1e0'
down_revision: Union[str, Sequence[str], None] = 'bd9575fb5b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('agent_config', sa.JSON(), nullable=False),
    sa.Column('model_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_owner_id'), 'user_settings', ['owner_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_owner_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
